# Generated by Django 3.0.4 on 2020-03-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredents',
            new_name='ingredients',
        ),
    ]
